### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by frol** [davidpdrsn/extend#1]
May I ask you to compare your crate to https://github.com/taiki-e/easy-ext?

**Comment by Boscop** [comment]
I've been using this crate until now: https://crates.io/crates/extension-trait
There's an [Initial procmacro implementation](https://gitlab.com/KonradBorowski/extension-trait/merge_requests/2).

**Comment by davidpdrsn** [comment]
I didn't see "easy-ext" on crates.io when I looked if something like this already existed. Don't remember exactly what I searched for. The docs for it failed to build so I cannot say exactly what all the differences are. However it seems _very_ similar to this.

Regarding "extension-trait". It uses a `macro_rules!` macro which means there is a bit of custom syntax to learn. This crate gets around that with an attribute proc-macro. I haven't looked into the proc-macro version, but I doubt they're changing the syntax since that would be a breaking change.
