### ISSUE TITLE
Generated traits don't support boxing

### ISSUE THREAD

**Issue by Boscop** [davidpdrsn/extend#7]
I wanted to replace this with an extension trait:
```rust
pub trait Persistable {
	fn persist_state(&self);
}

impl<T: Default + Clone + TypeName + Serialize + DeserializeOwned> Persistable for T {
	fn persist_state(&self) {
```
But this doesn't work:
```rust
#[ext(pub, name = Persistable)]
impl<T: Default + Clone + TypeName + Serialize + DeserializeOwned> T {
	fn persist_state(&self) {
```
When I have `Box<dyn Persistable>`, I get:
```
error: wrong number of type arguments: expected 1, found 0
error: expected 1 type argument
```
Why?

**Comment by davidpdrsn** [comment]
Not sure. Where does `TypeName` come from?

**Comment by davidpdrsn** [comment]
Ah wait I see why. The trait that gets generated includes the trait bounds from the impl:

```rust
pub trait Persistable<T: Default + ...> {
    fn persist_state(&self);
}
```

Not sure if changing this would break anything. I'll have to do some more tests.

**Comment by Boscop** [comment]
Thanks. It would be nice to generate it so that the generated trait doesn't have these bounds (only the impl).

**Comment by davidpdrsn** [comment]
Yes I agree. I suppose its fine as well since none of the methods in the trait have bodies (they're all on the impl). So nothing inside the trait definition can really use the bounds (afaik).

**Comment by davidpdrsn** [comment]
I have looked into this and its a bit more complicated than I first thought.

Its fairly simple getting an extension like this working:

```rust
#[ext(name = Ext)]
impl<T> T {
    fn some_method(&self) {}
}
```

The generated code should be:

```rust
trait Ext {
    fn some_method(&self);
}

impl<T> Ext for T   {
    fn some_method(&self) {}
}
```

However for a more complicated case like this it is it is not so simple:

```rust
trait OtherTrait<T> {}

#[ext(name = Ext)]
impl<'a, T: 'a + Default, K: 'a + Clone> T
where
    K: OtherTrait<T>,
    T: Clone,
{
    fn some_method(&self, _: Foo<K>) {}
}
```

In this case the generated code should be

```rust
trait Ext<'a, K: 'a + Clone>
where
    K: Copy,
{
    fn some_method(&self, _: Foo<K>) {}
}

impl<'a, T: 'a + Default, K: 'a + Clone> Ext<'a, K> for T
where
    K: Copy,
    T: Clone,
{
    fn some_method(&self, _: Foo<K>) {}
}
```

I think we would have to look at the self type thats being extended (the `T` in the example above) and find all references to that in the impl generics (everything inside `<...>`) and the where clause and remove it.

However that wouldn't work if the where clause includes a bound like this:

```rust
#[ext]
impl<T, K> T
where
    K: OtherTrait<T>,
{
    fn foo() {}
}
```

In this case we cannot remove references to `T` because it is used in this bound `K: OtherTrait<T>`. So in this case we would have to keep `T`. The generated code should be:

```rust
trait Ext<T, K>
where
    K: OtherTrait<T>,
{
    fn foo();
}

impl<T, K> Ext<T, K> for T
where
    K: OtherTrait<T>,
{
    fn foo() {}
}
```

There are probably other cases that I haven't thought of.

As you can see this isn't easy to fix in the general case. Therefore I'm tempted to consider this a use case we shouldn't support.

@Boscop What do you think?

**Comment by Boscop** [comment]
It would be sad if this use case wouldn't be supported because it occurs quite often (at least in my code). 
I don't think we need to do heavy analysis here, we could just allow specifying explicitly which bounds should be on the trait itself, through an argument to the derive macro.

**Comment by davidpdrsn** [comment]
Any suggestion to what the syntax should be?
